/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light mode - Enhanced contrast
        white: '#FFFFFF',
        'zinc-50': '#FAFAFA',
        'zinc-100': '#F4F4F5',
        'zinc-200': '#E4E4E7',
        'zinc-300': '#D4D4D8',
        'zinc-400': '#8F8F99',
        'zinc-500': '#6B6B74',
        'zinc-600': '#484851',
        'zinc-700': '#3A3A41',
        'zinc-800': '#27272A',
        'zinc-900': '#18181B',
        'zinc-950': '#09090B',
        black: '#000000',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.16' }],
        '6xl': ['3.75rem', { lineHeight: '1.12' }],
      },
      spacing: {
        0: '0',
        px: '1px',
        0.5: '0.125rem',
        1: '0.25rem',
        1.5: '0.375rem',
        2: '0.5rem',
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        96: '24rem',
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0em',
        wide: '0.01em',
        wider: '0.02em',
        widest: '0.05em',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.zinc.600'),
            '--tw-prose-headings': theme('colors.zinc.900'),
            '--tw-prose-links': theme('colors.zinc.900'),
            '--tw-prose-bold': theme('colors.zinc.900'),
            '--tw-prose-counters': theme('colors.zinc.700'),
            '--tw-prose-bullets': theme('colors.zinc.700'),
            '--tw-prose-quotes': theme('colors.zinc.900'),
            '--tw-prose-code': theme('colors.zinc.900'),
            '--tw-prose-hr': theme('colors.zinc.200'),
            '--tw-prose-th-borders': theme('colors.zinc.300'),
            '--tw-prose-td-borders': theme('colors.zinc.200'),

            // Dark mode
            '--tw-prose-invert-body': theme('colors.zinc.300'),
            '--tw-prose-invert-headings': theme('colors.zinc.100'),
            '--tw-prose-invert-links': theme('colors.zinc.100'),
            '--tw-prose-invert-bold': theme('colors.zinc.100'),
            '--tw-prose-invert-counters': theme('colors.zinc.300'),
            '--tw-prose-invert-bullets': theme('colors.zinc.300'),
            '--tw-prose-invert-quotes': theme('colors.zinc.100'),
            '--tw-prose-invert-code': theme('colors.zinc.100'),
            '--tw-prose-invert-hr': theme('colors.zinc.700'),
            '--tw-prose-invert-th-borders': theme('colors.zinc.600'),
            '--tw-prose-invert-td-borders': theme('colors.zinc.700'),
          },
        },
        invert: {
          css: {
            '--tw-prose-body': theme('colors.zinc.400'),
            '--tw-prose-headings': theme('colors.zinc.200'),
            '--tw-prose-links': theme('colors.zinc.200'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};